language: android
jdk: oraclejdk8
sudo: true
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.1
  - android-22
  - addon-$ANDROID_TAG-google-$ANDROID_API_LEVEL
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-$ANDROID_TARGET

script:
   - chmod +x gradlew
   - ./gradlew build
   - ./gradlew assembleRelease
